// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: oauth2as/internal/token/token.proto

package token

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TokenData struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_GrantId     *string                `protobuf:"bytes,1,opt,name=grant_id,json=grantId"`
	xxx_hidden_UserId      *string                `protobuf:"bytes,2,opt,name=user_id,json=userId"`
	xxx_hidden_TokenId     *string                `protobuf:"bytes,3,opt,name=token_id,json=tokenId"`
	xxx_hidden_Secret      []byte                 `protobuf:"bytes,4,opt,name=secret"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TokenData) Reset() {
	*x = TokenData{}
	mi := &file_oauth2as_internal_token_token_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenData) ProtoMessage() {}

func (x *TokenData) ProtoReflect() protoreflect.Message {
	mi := &file_oauth2as_internal_token_token_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TokenData) GetGrantId() string {
	if x != nil {
		if x.xxx_hidden_GrantId != nil {
			return *x.xxx_hidden_GrantId
		}
		return ""
	}
	return ""
}

func (x *TokenData) GetUserId() string {
	if x != nil {
		if x.xxx_hidden_UserId != nil {
			return *x.xxx_hidden_UserId
		}
		return ""
	}
	return ""
}

func (x *TokenData) GetTokenId() string {
	if x != nil {
		if x.xxx_hidden_TokenId != nil {
			return *x.xxx_hidden_TokenId
		}
		return ""
	}
	return ""
}

func (x *TokenData) GetSecret() []byte {
	if x != nil {
		return x.xxx_hidden_Secret
	}
	return nil
}

func (x *TokenData) SetGrantId(v string) {
	x.xxx_hidden_GrantId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *TokenData) SetUserId(v string) {
	x.xxx_hidden_UserId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *TokenData) SetTokenId(v string) {
	x.xxx_hidden_TokenId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *TokenData) SetSecret(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Secret = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *TokenData) HasGrantId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *TokenData) HasUserId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *TokenData) HasTokenId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *TokenData) HasSecret() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *TokenData) ClearGrantId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_GrantId = nil
}

func (x *TokenData) ClearUserId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_UserId = nil
}

func (x *TokenData) ClearTokenId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_TokenId = nil
}

func (x *TokenData) ClearSecret() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Secret = nil
}

type TokenData_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	GrantId *string
	UserId  *string
	TokenId *string
	Secret  []byte
}

func (b0 TokenData_builder) Build() *TokenData {
	m0 := &TokenData{}
	b, x := &b0, m0
	_, _ = b, x
	if b.GrantId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_GrantId = b.GrantId
	}
	if b.UserId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_UserId = b.UserId
	}
	if b.TokenId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_TokenId = b.TokenId
	}
	if b.Secret != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_Secret = b.Secret
	}
	return m0
}

var File_oauth2as_internal_token_token_proto protoreflect.FileDescriptor

const file_oauth2as_internal_token_token_proto_rawDesc = "" +
	"\n" +
	"#oauth2as/internal/token/token.proto\x12(lds.li.oauth2ext.oauth2as.internal.token\x1a!google/protobuf/go_features.proto\"r\n" +
	"\tTokenData\x12\x19\n" +
	"\bgrant_id\x18\x01 \x01(\tR\agrantId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x19\n" +
	"\btoken_id\x18\x03 \x01(\tR\atokenId\x12\x16\n" +
	"\x06secret\x18\x04 \x01(\fR\x06secretB2Z(lds.li/oauth2ext/oauth2as/internal/token\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_oauth2as_internal_token_token_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_oauth2as_internal_token_token_proto_goTypes = []any{
	(*TokenData)(nil), // 0: lds.li.oauth2ext.oauth2as.internal.token.TokenData
}
var file_oauth2as_internal_token_token_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_oauth2as_internal_token_token_proto_init() }
func file_oauth2as_internal_token_token_proto_init() {
	if File_oauth2as_internal_token_token_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_oauth2as_internal_token_token_proto_rawDesc), len(file_oauth2as_internal_token_token_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_oauth2as_internal_token_token_proto_goTypes,
		DependencyIndexes: file_oauth2as_internal_token_token_proto_depIdxs,
		MessageInfos:      file_oauth2as_internal_token_token_proto_msgTypes,
	}.Build()
	File_oauth2as_internal_token_token_proto = out.File
	file_oauth2as_internal_token_token_proto_goTypes = nil
	file_oauth2as_internal_token_token_proto_depIdxs = nil
}
