// Code generated by o2ext-claimgen. DO NOT EDIT.

package claims

import (
	"fmt"
	"maps"
	"slices"
	"time"

	"github.com/tink-crypto/tink-go/v2/jwt"
)

// VerifiedID represents the claims of an OIDC ID token
// https://openid.net/specs/openid-connect-core-1_0.html#IDToken
type VerifiedID struct {
	jwt *jwt.VerifiedJWT
}

// HasIssuer checks whether a JWT contains the issuer claim.
func (i *VerifiedID) HasIssuer() bool {
	return i.jwt.HasIssuer()
}

// Issuer returns the issuer claim ('iss') or an error if no claim is present.
func (i *VerifiedID) Issuer() (string, error) {
	return i.jwt.Issuer()
}

// HasSubject checks whether a JWT contains the subject claim.
func (i *VerifiedID) HasSubject() bool {
	return i.jwt.HasSubject()
}

// Subject returns the subject claim ('sub') or an error if no claim is present.
func (i *VerifiedID) Subject() (string, error) {
	return i.jwt.Subject()
}

// HasAudiences checks whether a JWT contains the audience claim ('aud').
func (i *VerifiedID) HasAudiences() bool {
	return i.jwt.HasAudiences()
}

// Audiences returns a list of audiences from the 'aud' claim. If the 'aud' claim is a single
// string, it is converted into a list with a single entry.
func (i *VerifiedID) Audiences() ([]string, error) {
	return i.jwt.Audiences()
}

// HasJWTID checks whether a JWT contains the jwtid claim.
func (i *VerifiedID) HasJWTID() bool {
	return i.jwt.HasJWTID()
}

// JWTID returns the JWT ID claim ('jti') or an error if no claim is present.
func (i *VerifiedID) JWTID() (string, error) {
	return i.jwt.JWTID()
}

// HasIssuedAt checks whether a JWT contains the issuedat claim.
func (i *VerifiedID) HasIssuedAt() bool {
	return i.jwt.HasIssuedAt()
}

// IssuedAt returns the issued at claim ('iat') or an error if no claim is present.
func (i *VerifiedID) IssuedAt() (time.Time, error) {
	return i.jwt.IssuedAt()
}

// HasExpiration checks whether a JWT contains the expiration claim.
func (i *VerifiedID) HasExpiration() bool {
	return i.jwt.HasExpiration()
}

// ExpiresAt returns the expiration claim ('exp') or an error if no claim is present.
func (i *VerifiedID) ExpiresAt() (time.Time, error) {
	return i.jwt.ExpiresAt()
}

// HasNotBefore checks whether a JWT contains the notbefore claim.
func (i *VerifiedID) HasNotBefore() bool {
	return i.jwt.HasNotBefore()
}

// NotBefore returns the not before claim ('nbf') or an error if no claim is present.
func (i *VerifiedID) NotBefore() (time.Time, error) {
	return i.jwt.NotBefore()
}

// JSONPayload marshals a VerifiedJWT payload to JSON.
func (i *VerifiedID) JSONPayload() ([]byte, error) {
	return i.jwt.JSONPayload()
}

// JWT returns the underlying VerifiedJWT.
func (i *VerifiedID) JWT() *jwt.VerifiedJWT {
	return i.jwt
}

const (
	idClaimName                = "name"
	idClaimGivenName           = "given_name"
	idClaimFamilyName          = "family_name"
	idClaimMiddleName          = "middle_name"
	idClaimNickname            = "nickname"
	idClaimPreferredUsername   = "preferred_username"
	idClaimProfile             = "profile"
	idClaimPicture             = "picture"
	idClaimWebsite             = "website"
	idClaimEmail               = "email"
	idClaimEmailVerified       = "email_verified"
	idClaimGender              = "gender"
	idClaimBirthdate           = "birthdate"
	idClaimZoneinfo            = "zoneinfo"
	idClaimLocale              = "locale"
	idClaimPhoneNumber         = "phone_number"
	idClaimPhoneNumberVerified = "phone_number_verified"
	idClaimAddress             = "address"
	idClaimUpdatedAt           = "updated_at"
	idClaimACR                 = "acr"
	idClaimAMR                 = "amr"
	idClaimAuthTime            = "auth_time"
	idClaimNonce               = "nonce"
	idClaimAtHash              = "at_hash"
	idClaimCHash               = "c_hash"
	idClaimSID                 = "sid"
)

// HasName checks whether the name claim is present.
func (i *VerifiedID) HasName() bool {
	return i.jwt.HasStringClaim(idClaimName)
}

// Name returns End-User's full name in displayable form including all name parts, possibly
// including titles and suffixes, ordered according to the End-User's locale and preferences.
func (i *VerifiedID) Name() (string, error) {
	return i.jwt.StringClaim(idClaimName)
}

// HasGivenName checks whether the given_name claim is present.
func (i *VerifiedID) HasGivenName() bool {
	return i.jwt.HasStringClaim(idClaimGivenName)
}

// GivenName returns Given name(s) or first name(s) of the End-User. Note that in some cultures,
// people can have multiple given names; all can be present, with the names being separated by space
// characters.
func (i *VerifiedID) GivenName() (string, error) {
	return i.jwt.StringClaim(idClaimGivenName)
}

// HasFamilyName checks whether the family_name claim is present.
func (i *VerifiedID) HasFamilyName() bool {
	return i.jwt.HasStringClaim(idClaimFamilyName)
}

// FamilyName returns Surname(s) or last name(s) of the End-User. Note that in some cultures, people
// can have multiple family names or no family name; all can be present, with the names being
// separated by space characters.
func (i *VerifiedID) FamilyName() (string, error) {
	return i.jwt.StringClaim(idClaimFamilyName)
}

// HasMiddleName checks whether the middle_name claim is present.
func (i *VerifiedID) HasMiddleName() bool {
	return i.jwt.HasStringClaim(idClaimMiddleName)
}

// MiddleName returns Middle name(s) of the End-User. Note that in some cultures, people can have
// multiple middle names; all can be present, with the names being separated by space characters.
// Also note that in some cultures, middle names are not used.
func (i *VerifiedID) MiddleName() (string, error) {
	return i.jwt.StringClaim(idClaimMiddleName)
}

// HasNickname checks whether the nickname claim is present.
func (i *VerifiedID) HasNickname() bool {
	return i.jwt.HasStringClaim(idClaimNickname)
}

// Nickname returns Casual name of the End-User that may or may not be the same as the given_name.
// For instance, a nickname value of Mike might be returned alongside a given_name value of Michael.
func (i *VerifiedID) Nickname() (string, error) {
	return i.jwt.StringClaim(idClaimNickname)
}

// HasPreferredUsername checks whether the preferred_username claim is present.
func (i *VerifiedID) HasPreferredUsername() bool {
	return i.jwt.HasStringClaim(idClaimPreferredUsername)
}

// PreferredUsername returns Shorthand name by which the End-User wishes to be referred to at the
// RP, such as janedoe or j.doe. This value MAY be any valid JSON string including special
// characters such as @, /, or whitespace. The RP MUST NOT rely upon this value being unique, as
// discussed in Section 5.7.
func (i *VerifiedID) PreferredUsername() (string, error) {
	return i.jwt.StringClaim(idClaimPreferredUsername)
}

// HasProfile checks whether the profile claim is present.
func (i *VerifiedID) HasProfile() bool {
	return i.jwt.HasStringClaim(idClaimProfile)
}

// Profile returns URL of the End-User's profile page. The contents of this Web page SHOULD be about
// the End-User.
func (i *VerifiedID) Profile() (string, error) {
	return i.jwt.StringClaim(idClaimProfile)
}

// HasPicture checks whether the picture claim is present.
func (i *VerifiedID) HasPicture() bool {
	return i.jwt.HasStringClaim(idClaimPicture)
}

// Picture returns URL of the End-User's profile picture. This URL MUST refer to an image file (for
// example, a PNG, JPEG, or GIF image file), rather than to a Web page containing an image. Note
// that this URL SHOULD specifically reference a profile photo of the End-User suitable for
// displaying when describing the End-User, rather than an arbitrary photo taken by the End-User.
func (i *VerifiedID) Picture() (string, error) {
	return i.jwt.StringClaim(idClaimPicture)
}

// HasWebsite checks whether the website claim is present.
func (i *VerifiedID) HasWebsite() bool {
	return i.jwt.HasStringClaim(idClaimWebsite)
}

// Website returns URL of the End-User's Web page or blog. This Web page SHOULD contain information
// published by the End-User or an organization that the End-User is affiliated with.
func (i *VerifiedID) Website() (string, error) {
	return i.jwt.StringClaim(idClaimWebsite)
}

// HasEmail checks whether the email claim is present.
func (i *VerifiedID) HasEmail() bool {
	return i.jwt.HasStringClaim(idClaimEmail)
}

// Email returns End-User's preferred e-mail address. Its value MUST conform to the RFC 5322
// [RFC5322] addr-spec syntax. The RP MUST NOT rely upon this value being unique, as discussed in
// Section 5.7.
func (i *VerifiedID) Email() (string, error) {
	return i.jwt.StringClaim(idClaimEmail)
}

// HasEmailVerified checks whether the email_verified claim is present.
func (i *VerifiedID) HasEmailVerified() bool {
	return i.jwt.HasBooleanClaim(idClaimEmailVerified)
}

// EmailVerified returns True if the End-User's e-mail address has been verified; otherwise false.
// When this Claim Value is true, this means that the OP took affirmative steps to ensure that this
// e-mail address was controlled by the End-User at the time the verification was performed. The
// means by which an e-mail address is verified is context specific, and dependent upon the trust
// framework or contractual agreements within which the parties are operating.
func (i *VerifiedID) EmailVerified() (bool, error) {
	return i.jwt.BooleanClaim(idClaimEmailVerified)
}

// HasGender checks whether the gender claim is present.
func (i *VerifiedID) HasGender() bool {
	return i.jwt.HasStringClaim(idClaimGender)
}

// Gender returns End-User's gender. Values defined by this specification are female and male. Other
// values MAY be used when neither of the defined values are applicable.
func (i *VerifiedID) Gender() (string, error) {
	return i.jwt.StringClaim(idClaimGender)
}

// HasBirthdate checks whether the birthdate claim is present.
func (i *VerifiedID) HasBirthdate() bool {
	return i.jwt.HasStringClaim(idClaimBirthdate)
}

// Birthdate returns End-User's birthday, represented as an ISO 8601-1 [ISO8601‑1] YYYY-MM-DD
// format. The year MAY be 0000, indicating that it is omitted. To represent only the year, YYYY
// format is allowed. Note that depending on the underlying platform's date related function,
// providing just year can result in varying month and day, so the implementers need to take this
// factor into account to correctly process the dates.
func (i *VerifiedID) Birthdate() (string, error) {
	return i.jwt.StringClaim(idClaimBirthdate)
}

// HasZoneinfo checks whether the zoneinfo claim is present.
func (i *VerifiedID) HasZoneinfo() bool {
	return i.jwt.HasStringClaim(idClaimZoneinfo)
}

// Zoneinfo returns String from IANA Time Zone Database [IANA.time‑zones] representing the
// End-User's time zone. For example, Europe/Paris or America/Los_Angeles.
func (i *VerifiedID) Zoneinfo() (string, error) {
	return i.jwt.StringClaim(idClaimZoneinfo)
}

// HasLocale checks whether the locale claim is present.
func (i *VerifiedID) HasLocale() bool {
	return i.jwt.HasStringClaim(idClaimLocale)
}

// Locale returns End-User's locale, represented as a BCP47 [RFC5646] language tag. This is
// typically an ISO 639 Alpha-2 [ISO639] language code in lowercase and an ISO 3166-1 Alpha-2
// [ISO3166‑1] country code in uppercase, separated by a dash. For example, en-US or fr-CA. As a
// compatibility note, some implementations have used an underscore as the separator rather than a
// dash, for example, en_US; Relying Parties MAY choose to accept this locale syntax as well.
func (i *VerifiedID) Locale() (string, error) {
	return i.jwt.StringClaim(idClaimLocale)
}

// HasPhoneNumber checks whether the phone_number claim is present.
func (i *VerifiedID) HasPhoneNumber() bool {
	return i.jwt.HasStringClaim(idClaimPhoneNumber)
}

// PhoneNumber returns End-User's preferred telephone number. E.164 [E.164] is RECOMMENDED as the
// format of this Claim, for example, +1 (425) 555-1212 or +56 (2) 687 2400. If the phone number
// contains an extension, it is RECOMMENDED that the extension be represented using the RFC 3966
// [RFC3966] extension syntax, for example, +1 (604) 555-1234;ext=5678.
func (i *VerifiedID) PhoneNumber() (string, error) {
	return i.jwt.StringClaim(idClaimPhoneNumber)
}

// HasPhoneNumberVerified checks whether the phone_number_verified claim is present.
func (i *VerifiedID) HasPhoneNumberVerified() bool {
	return i.jwt.HasBooleanClaim(idClaimPhoneNumberVerified)
}

// PhoneNumberVerified returns True if the End-User's phone number has been verified; otherwise
// false. When this Claim Value is true, this means that the OP took affirmative steps to ensure
// that this phone number was controlled by the End-User at the time the verification was performed.
// The means by which a phone number is verified is context specific, and dependent upon the trust
// framework or contractual agreements within which the parties are operating. When true, the
// phone_number Claim MUST be in E.164 format and any extensions MUST be represented in RFC 3966
// format.
func (i *VerifiedID) PhoneNumberVerified() (bool, error) {
	return i.jwt.BooleanClaim(idClaimPhoneNumberVerified)
}

// HasAddress checks whether the address claim is present.
func (i *VerifiedID) HasAddress() bool {
	return i.jwt.HasObjectClaim(idClaimAddress)
}

// Address returns End-User's preferred postal address. The value of the address member is a JSON
// [RFC8259] structure containing some or all of the members defined in Section 5.1.1.
func (i *VerifiedID) Address() (map[string]any, error) {
	return i.jwt.ObjectClaim(idClaimAddress)
}

// HasUpdatedAt checks whether the updated_at claim is present.
func (i *VerifiedID) HasUpdatedAt() bool {
	return i.jwt.HasNumberClaim(idClaimUpdatedAt)
}

// UpdatedAt returns Time the End-User's information was last updated. Its value is a JSON number
// representing the number of seconds from 1970-01-01T00:00:00Z as measured in UTC until the
// date/time.
func (i *VerifiedID) UpdatedAt() (time.Time, error) {
	ts, err := i.jwt.NumberClaim(idClaimUpdatedAt)
	if err != nil {
		return time.Time{}, err
	}
	return time.Unix(int64(ts), 0).UTC(), nil
}

// HasACR checks whether the acr claim is present.
func (i *VerifiedID) HasACR() bool {
	return i.jwt.HasStringClaim(idClaimACR)
}

// ACR returns Authentication Context Class Reference. This claim specifies the authentication
// context class that the authentication performed satisfied.
func (i *VerifiedID) ACR() (string, error) {
	return i.jwt.StringClaim(idClaimACR)
}

// HasAMR checks whether the amr claim is present.
func (i *VerifiedID) HasAMR() bool {
	return i.jwt.HasArrayClaim(idClaimAMR)
}

// AMR returns Authentication Methods References. This is an array of strings that are identifiers
// for authentication methods used in the authentication. For example, values might include "pwd"
// for password, "otp" for one-time password, etc.
func (i *VerifiedID) AMR() ([]string, error) {
	arr, err := i.jwt.ArrayClaim(idClaimAMR)
	if err != nil {
		return nil, err
	}
	result := make([]string, len(arr))
	for i, v := range arr {
		s, ok := v.(string)
		if !ok {
			return nil, fmt.Errorf("element %d is not a string", i)
		}
		result[i] = s
	}
	return result, nil
}

// HasAuthTime checks whether the auth_time claim is present.
func (i *VerifiedID) HasAuthTime() bool {
	return i.jwt.HasNumberClaim(idClaimAuthTime)
}

// AuthTime returns Time when the End-User authentication occurred. Its value is a JSON number
// representing the number of seconds from 1970-01-01T00:00:00Z as measured in UTC until the
// date/time.
func (i *VerifiedID) AuthTime() (time.Time, error) {
	ts, err := i.jwt.NumberClaim(idClaimAuthTime)
	if err != nil {
		return time.Time{}, err
	}
	return time.Unix(int64(ts), 0).UTC(), nil
}

// HasNonce checks whether the nonce claim is present.
func (i *VerifiedID) HasNonce() bool {
	return i.jwt.HasStringClaim(idClaimNonce)
}

// Nonce returns String value used to associate a Client session with an ID Token, and to mitigate
// replay attacks. The nonce value is passed through unmodified from the Authentication Request to
// the ID Token.
func (i *VerifiedID) Nonce() (string, error) {
	return i.jwt.StringClaim(idClaimNonce)
}

// HasAtHash checks whether the at_hash claim is present.
func (i *VerifiedID) HasAtHash() bool {
	return i.jwt.HasStringClaim(idClaimAtHash)
}

// AtHash returns Access Token hash value. Its value is the base64url encoding of the left-most half
// of the hash of the octets of the ASCII representation of the access_token value, where the hash
// algorithm used is the hash algorithm used in the alg Header Parameter of the ID Token's JOSE
// Header.
func (i *VerifiedID) AtHash() (string, error) {
	return i.jwt.StringClaim(idClaimAtHash)
}

// HasCHash checks whether the c_hash claim is present.
func (i *VerifiedID) HasCHash() bool {
	return i.jwt.HasStringClaim(idClaimCHash)
}

// CHash returns Code hash value. Its value is the base64url encoding of the left-most half of the
// hash of the octets of the ASCII representation of the code value, where the hash algorithm used
// is the hash algorithm used in the alg Header Parameter of the ID Token's JOSE Header.
func (i *VerifiedID) CHash() (string, error) {
	return i.jwt.StringClaim(idClaimCHash)
}

// HasSID checks whether the sid claim is present.
func (i *VerifiedID) HasSID() bool {
	return i.jwt.HasStringClaim(idClaimSID)
}

// SID returns Session ID. This is a string identifier for a Session. This represents a Session of a
// User Agent or device for a logged-in End-User at an RP. Different sid values are used to identify
// distinct sessions at an OP. The sid value need only be unique in the context of a particular
// issuer.
func (i *VerifiedID) SID() (string, error) {
	return i.jwt.StringClaim(idClaimSID)
}

var reservedIDClaims = []string{
	idClaimName,
	idClaimGivenName,
	idClaimFamilyName,
	idClaimMiddleName,
	idClaimNickname,
	idClaimPreferredUsername,
	idClaimProfile,
	idClaimPicture,
	idClaimWebsite,
	idClaimEmail,
	idClaimEmailVerified,
	idClaimGender,
	idClaimBirthdate,
	idClaimZoneinfo,
	idClaimLocale,
	idClaimPhoneNumber,
	idClaimPhoneNumberVerified,
	idClaimAddress,
	idClaimUpdatedAt,
	idClaimACR,
	idClaimAMR,
	idClaimAuthTime,
	idClaimNonce,
	idClaimAtHash,
	idClaimCHash,
	idClaimSID,
}

// HasStringClaim checks whether a claim of type string is present.
func (i *VerifiedID) HasStringClaim(name string) bool {
	return i.jwt.HasStringClaim(name)
}

// StringClaim returns a custom string claim or an error if no claim is present.
// Reserved claims should be accessed using their specific methods.
func (i *VerifiedID) StringClaim(name string) (string, error) {
	if isReservedIDClaim(name) {
		return "", fmt.Errorf("claim %s is reserved", name)
	}
	return i.jwt.StringClaim(name)
}

// HasNumberClaim checks whether a claim of type number is present.
func (i *VerifiedID) HasNumberClaim(name string) bool {
	return i.jwt.HasNumberClaim(name)
}

// NumberClaim returns a custom number claim or an error if no claim is present.
// Reserved claims should be accessed using their specific methods.
func (i *VerifiedID) NumberClaim(name string) (float64, error) {
	if isReservedIDClaim(name) {
		return 0, fmt.Errorf("claim %s is reserved", name)
	}
	return i.jwt.NumberClaim(name)
}

// HasBooleanClaim checks whether a claim of type bool is present.
func (i *VerifiedID) HasBooleanClaim(name string) bool {
	return i.jwt.HasBooleanClaim(name)
}

// BooleanClaim returns a custom bool claim or an error if no claim is present.
// Reserved claims should be accessed using their specific methods.
func (i *VerifiedID) BooleanClaim(name string) (bool, error) {
	if isReservedIDClaim(name) {
		return false, fmt.Errorf("claim %s is reserved", name)
	}
	return i.jwt.BooleanClaim(name)
}

// HasNullClaim checks whether a claim of type null is present.
func (i *VerifiedID) HasNullClaim(name string) bool {
	return i.jwt.HasNullClaim(name)
}

// HasArrayClaim checks whether a claim of type list is present.
func (i *VerifiedID) HasArrayClaim(name string) bool {
	return i.jwt.HasArrayClaim(name)
}

// ArrayClaim returns a slice representing a JSON array for a claim or an error if the claim is empty.
// Reserved claims should be accessed using their specific methods.
func (i *VerifiedID) ArrayClaim(name string) ([]any, error) {
	if isReservedIDClaim(name) {
		return nil, fmt.Errorf("claim %s is reserved", name)
	}
	return i.jwt.ArrayClaim(name)
}

// HasObjectClaim checks whether a claim of type object is present.
func (i *VerifiedID) HasObjectClaim(name string) bool {
	return i.jwt.HasObjectClaim(name)
}

// ObjectClaim returns a map representing a JSON object for a claim or an error if the claim is empty.
// Reserved claims should be accessed using their specific methods.
func (i *VerifiedID) ObjectClaim(name string) (map[string]any, error) {
	if isReservedIDClaim(name) {
		return nil, fmt.Errorf("claim %s is reserved", name)
	}
	return i.jwt.ObjectClaim(name)
}

// CustomClaimNames returns a list with the name of custom claims in a VerifiedJWT.
func (i *VerifiedID) CustomClaimNames() []string {
	return i.jwt.CustomClaimNames()
}

func isReservedIDClaim(name string) bool {
	return slices.Contains(reservedIDClaims, name)
}

type RawIDOptions struct {
	Issuer    *string
	ClientID  *string
	Subject   *string
	JWTID     *string
	IssuedAt  *time.Time
	ExpiresAt *time.Time
	NotBefore *time.Time
	// Name is End-User's full name in displayable form including all name parts, possibly including
	// titles and suffixes, ordered according to the End-User's locale and preferences.
	Name *string
	// GivenName is Given name(s) or first name(s) of the End-User. Note that in some cultures,
	// people can have multiple given names; all can be present, with the names being separated by
	// space characters.
	GivenName *string
	// FamilyName is Surname(s) or last name(s) of the End-User. Note that in some cultures, people
	// can have multiple family names or no family name; all can be present, with the names being
	// separated by space characters.
	FamilyName *string
	// MiddleName is Middle name(s) of the End-User. Note that in some cultures, people can have
	// multiple middle names; all can be present, with the names being separated by space
	// characters. Also note that in some cultures, middle names are not used.
	MiddleName *string
	// Nickname is Casual name of the End-User that may or may not be the same as the given_name.
	// For instance, a nickname value of Mike might be returned alongside a given_name value of
	// Michael.
	Nickname *string
	// PreferredUsername is Shorthand name by which the End-User wishes to be referred to at the RP,
	// such as janedoe or j.doe. This value MAY be any valid JSON string including special
	// characters such as @, /, or whitespace. The RP MUST NOT rely upon this value being unique, as
	// discussed in Section 5.7.
	PreferredUsername *string
	// Profile is URL of the End-User's profile page. The contents of this Web page SHOULD be about
	// the End-User.
	Profile *string
	// Picture is URL of the End-User's profile picture. This URL MUST refer to an image file (for
	// example, a PNG, JPEG, or GIF image file), rather than to a Web page containing an image. Note
	// that this URL SHOULD specifically reference a profile photo of the End-User suitable for
	// displaying when describing the End-User, rather than an arbitrary photo taken by the
	// End-User.
	Picture *string
	// Website is URL of the End-User's Web page or blog. This Web page SHOULD contain information
	// published by the End-User or an organization that the End-User is affiliated with.
	Website *string
	// Email is End-User's preferred e-mail address. Its value MUST conform to the RFC 5322
	// [RFC5322] addr-spec syntax. The RP MUST NOT rely upon this value being unique, as discussed
	// in Section 5.7.
	Email *string
	// EmailVerified is True if the End-User's e-mail address has been verified; otherwise false.
	// When this Claim Value is true, this means that the OP took affirmative steps to ensure that
	// this e-mail address was controlled by the End-User at the time the verification was
	// performed. The means by which an e-mail address is verified is context specific, and
	// dependent upon the trust framework or contractual agreements within which the parties are
	// operating.
	EmailVerified *bool
	// Gender is End-User's gender. Values defined by this specification are female and male. Other
	// values MAY be used when neither of the defined values are applicable.
	Gender *string
	// Birthdate is End-User's birthday, represented as an ISO 8601-1 [ISO8601‑1] YYYY-MM-DD
	// format. The year MAY be 0000, indicating that it is omitted. To represent only the year, YYYY
	// format is allowed. Note that depending on the underlying platform's date related function,
	// providing just year can result in varying month and day, so the implementers need to take
	// this factor into account to correctly process the dates.
	Birthdate *string
	// Zoneinfo is String from IANA Time Zone Database [IANA.time‑zones] representing the
	// End-User's time zone. For example, Europe/Paris or America/Los_Angeles.
	Zoneinfo *string
	// Locale is End-User's locale, represented as a BCP47 [RFC5646] language tag. This is typically
	// an ISO 639 Alpha-2 [ISO639] language code in lowercase and an ISO 3166-1 Alpha-2
	// [ISO3166‑1] country code in uppercase, separated by a dash. For example, en-US or fr-CA. As
	// a compatibility note, some implementations have used an underscore as the separator rather
	// than a dash, for example, en_US; Relying Parties MAY choose to accept this locale syntax as
	// well.
	Locale *string
	// PhoneNumber is End-User's preferred telephone number. E.164 [E.164] is RECOMMENDED as the
	// format of this Claim, for example, +1 (425) 555-1212 or +56 (2) 687 2400. If the phone number
	// contains an extension, it is RECOMMENDED that the extension be represented using the RFC 3966
	// [RFC3966] extension syntax, for example, +1 (604) 555-1234;ext=5678.
	PhoneNumber *string
	// PhoneNumberVerified is True if the End-User's phone number has been verified; otherwise
	// false. When this Claim Value is true, this means that the OP took affirmative steps to ensure
	// that this phone number was controlled by the End-User at the time the verification was
	// performed. The means by which a phone number is verified is context specific, and dependent
	// upon the trust framework or contractual agreements within which the parties are operating.
	// When true, the phone_number Claim MUST be in E.164 format and any extensions MUST be
	// represented in RFC 3966 format.
	PhoneNumberVerified *bool
	// Address is End-User's preferred postal address. The value of the address member is a JSON
	// [RFC8259] structure containing some or all of the members defined in Section 5.1.1.
	Address map[string]any
	// UpdatedAt is Time the End-User's information was last updated. Its value is a JSON number
	// representing the number of seconds from 1970-01-01T00:00:00Z as measured in UTC until the
	// date/time.
	UpdatedAt *time.Time
	// ACR is Authentication Context Class Reference. This claim specifies the authentication
	// context class that the authentication performed satisfied.
	ACR *string
	// AMR is Authentication Methods References. This is an array of strings that are identifiers
	// for authentication methods used in the authentication. For example, values might include
	// "pwd" for password, "otp" for one-time password, etc.
	AMR []string
	// AuthTime is Time when the End-User authentication occurred. Its value is a JSON number
	// representing the number of seconds from 1970-01-01T00:00:00Z as measured in UTC until the
	// date/time.
	AuthTime *time.Time
	// Nonce is String value used to associate a Client session with an ID Token, and to mitigate
	// replay attacks. The nonce value is passed through unmodified from the Authentication Request
	// to the ID Token.
	Nonce *string
	// AtHash is Access Token hash value. Its value is the base64url encoding of the left-most half
	// of the hash of the octets of the ASCII representation of the access_token value, where the
	// hash algorithm used is the hash algorithm used in the alg Header Parameter of the ID Token's
	// JOSE Header.
	AtHash *string
	// CHash is Code hash value. Its value is the base64url encoding of the left-most half of the
	// hash of the octets of the ASCII representation of the code value, where the hash algorithm
	// used is the hash algorithm used in the alg Header Parameter of the ID Token's JOSE Header.
	CHash *string
	// SID is Session ID. This is a string identifier for a Session. This represents a Session of a
	// User Agent or device for a logged-in End-User at an RP. Different sid values are used to
	// identify distinct sessions at an OP. The sid value need only be unique in the context of a
	// particular issuer.
	SID *string
	// CustomClaims contains additional custom claims to include in the JWT.
	// These claims will be merged with the standard and extended claims.
	CustomClaims map[string]any
}

func (r *RawIDOptions) JWTOptions() (*jwt.RawJWTOptions, error) {
	// Check that CustomClaims doesn't contain any reserved claims
	for name := range r.CustomClaims {
		if isReservedIDClaim(name) {
			return nil, fmt.Errorf("claim %q is reserved and must be set via struct fields, not CustomClaims", name)
		}
	}
	convertStringSlice := func(s []string) []any {
		if s == nil {
			return nil
		}
		result := make([]any, len(s))
		for i, v := range s {
			result[i] = v
		}
		return result
	}

	o := &jwt.RawJWTOptions{
		Issuer:       r.Issuer,
		Audience:     r.ClientID,
		Subject:      r.Subject,
		IssuedAt:     r.IssuedAt,
		ExpiresAt:    r.ExpiresAt,
		NotBefore:    r.NotBefore,
		CustomClaims: maps.Clone(r.CustomClaims),
	}

	if o.CustomClaims == nil {
		o.CustomClaims = make(map[string]any)
	}
	if r.Name != nil {
		o.CustomClaims[idClaimName] = *r.Name
	}
	if r.GivenName != nil {
		o.CustomClaims[idClaimGivenName] = *r.GivenName
	}
	if r.FamilyName != nil {
		o.CustomClaims[idClaimFamilyName] = *r.FamilyName
	}
	if r.MiddleName != nil {
		o.CustomClaims[idClaimMiddleName] = *r.MiddleName
	}
	if r.Nickname != nil {
		o.CustomClaims[idClaimNickname] = *r.Nickname
	}
	if r.PreferredUsername != nil {
		o.CustomClaims[idClaimPreferredUsername] = *r.PreferredUsername
	}
	if r.Profile != nil {
		o.CustomClaims[idClaimProfile] = *r.Profile
	}
	if r.Picture != nil {
		o.CustomClaims[idClaimPicture] = *r.Picture
	}
	if r.Website != nil {
		o.CustomClaims[idClaimWebsite] = *r.Website
	}
	if r.Email != nil {
		o.CustomClaims[idClaimEmail] = *r.Email
	}
	if r.EmailVerified != nil {
		o.CustomClaims[idClaimEmailVerified] = *r.EmailVerified
	}
	if r.Gender != nil {
		o.CustomClaims[idClaimGender] = *r.Gender
	}
	if r.Birthdate != nil {
		o.CustomClaims[idClaimBirthdate] = *r.Birthdate
	}
	if r.Zoneinfo != nil {
		o.CustomClaims[idClaimZoneinfo] = *r.Zoneinfo
	}
	if r.Locale != nil {
		o.CustomClaims[idClaimLocale] = *r.Locale
	}
	if r.PhoneNumber != nil {
		o.CustomClaims[idClaimPhoneNumber] = *r.PhoneNumber
	}
	if r.PhoneNumberVerified != nil {
		o.CustomClaims[idClaimPhoneNumberVerified] = *r.PhoneNumberVerified
	}
	if r.Address != nil {
		o.CustomClaims[idClaimAddress] = r.Address
	}
	if r.UpdatedAt != nil {
		o.CustomClaims[idClaimUpdatedAt] = r.UpdatedAt.Unix()
	}
	if r.ACR != nil {
		o.CustomClaims[idClaimACR] = *r.ACR
	}
	if r.AMR != nil {
		o.CustomClaims[idClaimAMR] = convertStringSlice(r.AMR)
	}
	if r.AuthTime != nil {
		o.CustomClaims[idClaimAuthTime] = r.AuthTime.Unix()
	}
	if r.Nonce != nil {
		o.CustomClaims[idClaimNonce] = *r.Nonce
	}
	if r.AtHash != nil {
		o.CustomClaims[idClaimAtHash] = *r.AtHash
	}
	if r.CHash != nil {
		o.CustomClaims[idClaimCHash] = *r.CHash
	}
	if r.SID != nil {
		o.CustomClaims[idClaimSID] = *r.SID
	}

	return o, nil
}
